### ISSUE TITLE
Wanted New Feature :  Intelligent automated book renew

### ISSUE THREAD

**Issue by CreatorFan** [Cyphexl/WePeiYang-RN#1]
周神，想要一个功能：智能自动续借图书
简单地说就是，临近到期自动续借
有的时候，即使有临近到期的提醒，可能也会因为忙碌忘记，所以不如直接自动续借
这样的话，就可以直接实现长期借书，省去中间手动续借的困扰了
希望考虑下

**Comment by Cyphexl** [comment]
The book auto renew feature should be integrated into WePeiyang app after it is implemented in its server-side APIs. Please suggest this feature in our [mobile/open API](https://git.twtstudio.com/mobile/open) repository.

But we may need further discussion here. This feature sounds good, but it dramatically lowers the cost of continuously occupying a book. If all of our students enabled it (and apparently they would), then there would be no difference with a 3-month default loan period policy. I don't know how most people feels about this, but to me, I don't particularly like one guy holding a book for a long time and making others have to wait to access it.

For WePeiyang app itself, this would provide a good reason for people to install & use it. But we need to make sure it does not do anything "evil" before it does anything useful.

Anyway, thanks for your feedback =)
